# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\kursach_NEW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Deikstra_Monte_Karlo_Task_Window(object):
    def setupUi(self, Deikstra_Monte_Karlo_Task_Window):
        Deikstra_Monte_Karlo_Task_Window.setObjectName("Deikstra_Monte_Karlo_Task_Window")
        Deikstra_Monte_Karlo_Task_Window.resize(1311, 916)
        self.centralwidget = QtWidgets.QWidget(Deikstra_Monte_Karlo_Task_Window)
        self.centralwidget.setMaximumSize(QtCore.QSize(1318, 919))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1311, 891))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.main_layout_horizontal = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.main_layout_horizontal.setContentsMargins(0, 0, 0, 0)
        self.main_layout_horizontal.setObjectName("main_layout_horizontal")
        self.deikstra_layout_vertical = QtWidgets.QVBoxLayout()
        self.deikstra_layout_vertical.setObjectName("deikstra_layout_vertical")
        self.vvod_param_layout_horizontal = QtWidgets.QHBoxLayout()
        self.vvod_param_layout_horizontal.setObjectName("vvod_param_layout_horizontal")
        self.vvod_tochek_layout_grid = QtWidgets.QGridLayout()
        self.vvod_tochek_layout_grid.setSpacing(7)
        self.vvod_tochek_layout_grid.setObjectName("vvod_tochek_layout_grid")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.kolvo_vershin_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.kolvo_vershin_label.setAlignment(QtCore.Qt.AlignCenter)
        self.kolvo_vershin_label.setObjectName("kolvo_vershin_label")
        self.gridLayout.addWidget(self.kolvo_vershin_label, 0, 0, 1, 1)
        self.start_point_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.start_point_lineedit.setMaximumSize(QtCore.QSize(100, 25))
        self.start_point_lineedit.setObjectName("start_point_lineedit")
        self.gridLayout.addWidget(self.start_point_lineedit, 2, 3, 1, 1)
        self.start_point_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.start_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.start_point_label.setObjectName("start_point_label")
        self.gridLayout.addWidget(self.start_point_label, 0, 3, 1, 1)
        self.deikstra_draw_graph_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deikstra_draw_graph_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.deikstra_draw_graph_button.setStyleSheet("QPushButton#evilButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.deikstra_draw_graph_button.setObjectName("deikstra_draw_graph_button")
        self.gridLayout.addWidget(self.deikstra_draw_graph_button, 0, 5, 1, 1)
        self.kolvo_vershin_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kolvo_vershin_lineedit.sizePolicy().hasHeightForWidth())
        self.kolvo_vershin_lineedit.setSizePolicy(sizePolicy)
        self.kolvo_vershin_lineedit.setMaximumSize(QtCore.QSize(100, 25))
        self.kolvo_vershin_lineedit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kolvo_vershin_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.kolvo_vershin_lineedit.setObjectName("kolvo_vershin_lineedit")
        self.gridLayout.addWidget(self.kolvo_vershin_lineedit, 2, 0, 1, 1)
        self.end_point_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.end_point_label.setEnabled(True)
        self.end_point_label.setAutoFillBackground(False)
        self.end_point_label.setScaledContents(False)
        self.end_point_label.setAlignment(QtCore.Qt.AlignCenter)
        self.end_point_label.setObjectName("end_point_label")
        self.gridLayout.addWidget(self.end_point_label, 0, 2, 1, 1)
        self.autogeneration_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.autogeneration_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.autogeneration_button.setStyleSheet("QPushButton#evilButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.autogeneration_button.setObjectName("autogeneration_button")
        self.gridLayout.addWidget(self.autogeneration_button, 2, 5, 1, 1)
        self.end_point_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.end_point_lineedit.setMaximumSize(QtCore.QSize(100, 25))
        self.end_point_lineedit.setObjectName("end_point_lineedit")
        self.gridLayout.addWidget(self.end_point_lineedit, 2, 2, 1, 1)
        self.find_optimum_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.find_optimum_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.find_optimum_button.setStyleSheet("QPushButton#evilButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.find_optimum_button.setObjectName("find_optimum_button")
        self.gridLayout.addWidget(self.find_optimum_button, 0, 6, 1, 1)
        self.vvod_tochek_layout_grid.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.vvod_param_layout_horizontal.addLayout(self.vvod_tochek_layout_grid)
        self.deikstra_layout_vertical.addLayout(self.vvod_param_layout_horizontal)
        self.vvod_matrix_textedit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.vvod_matrix_textedit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.vvod_matrix_textedit.setObjectName("vvod_matrix_textedit")
        self.deikstra_layout_vertical.addWidget(self.vvod_matrix_textedit)
        self.deikstra_graph = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.deikstra_graph.setMinimumSize(QtCore.QSize(0, 420))
        self.deikstra_graph.setMaximumSize(QtCore.QSize(16777215, 420))
        self.deikstra_graph.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.deikstra_graph.setObjectName("deikstra_graph")
        self.deikstra_layout_vertical.addWidget(self.deikstra_graph)
        self.deikstra_view_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deikstra_view_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.deikstra_view_button.setStyleSheet("QPushButton#evilButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.deikstra_view_button.setObjectName("deikstra_view_button")
        self.deikstra_layout_vertical.addWidget(self.deikstra_view_button)
        self.main_layout_horizontal.addLayout(self.deikstra_layout_vertical)
        self.monte_karlo_layout_vertical = QtWidgets.QVBoxLayout()
        self.monte_karlo_layout_vertical.setObjectName("monte_karlo_layout_vertical")
        self.vvod_param_layout_grid = QtWidgets.QGridLayout()
        self.vvod_param_layout_grid.setObjectName("vvod_param_layout_grid")
        self.radius_porazh_VTO_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.radius_porazh_VTO_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.radius_porazh_VTO_lineedit.setObjectName("radius_porazh_VTO_lineedit")
        self.vvod_param_layout_grid.addWidget(self.radius_porazh_VTO_lineedit, 3, 1, 1, 1)
        self.avg_percent_damage_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.avg_percent_damage_label.setObjectName("avg_percent_damage_label")
        self.vvod_param_layout_grid.addWidget(self.avg_percent_damage_label, 6, 0, 1, 1)
        self.kolvo_zelei_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.kolvo_zelei_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.kolvo_zelei_lineedit.setObjectName("kolvo_zelei_lineedit")
        self.vvod_param_layout_grid.addWidget(self.kolvo_zelei_lineedit, 0, 1, 1, 1)
        self.kolvo_VTO_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.kolvo_VTO_label.setObjectName("kolvo_VTO_label")
        self.vvod_param_layout_grid.addWidget(self.kolvo_VTO_label, 1, 0, 1, 1)
        self.SKO_VTO_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.SKO_VTO_label.setObjectName("SKO_VTO_label")
        self.vvod_param_layout_grid.addWidget(self.SKO_VTO_label, 5, 0, 1, 1)
        self.kolvo_ispitaniy_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.kolvo_ispitaniy_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.kolvo_ispitaniy_lineedit.setObjectName("kolvo_ispitaniy_lineedit")
        self.vvod_param_layout_grid.addWidget(self.kolvo_ispitaniy_lineedit, 2, 1, 1, 1)
        self.kolvo_ispitaniy_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.kolvo_ispitaniy_label.setObjectName("kolvo_ispitaniy_label")
        self.vvod_param_layout_grid.addWidget(self.kolvo_ispitaniy_label, 2, 0, 1, 1)
        self.radius_porazh_VTO_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.radius_porazh_VTO_label.setObjectName("radius_porazh_VTO_label")
        self.vvod_param_layout_grid.addWidget(self.radius_porazh_VTO_label, 3, 0, 1, 1)
        self.veroyat_porazh_vseh_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.veroyat_porazh_vseh_label.setObjectName("veroyat_porazh_vseh_label")
        self.vvod_param_layout_grid.addWidget(self.veroyat_porazh_vseh_label, 7, 0, 1, 1)
        self.kolvo_VTO_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.kolvo_VTO_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.kolvo_VTO_lineedit.setObjectName("kolvo_VTO_lineedit")
        self.vvod_param_layout_grid.addWidget(self.kolvo_VTO_lineedit, 1, 1, 1, 1)
        self.dalnost_poleta_VTO_lineedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.dalnost_poleta_VTO_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.dalnost_poleta_VTO_lineedit.setObjectName("dalnost_poleta_VTO_lineedit")
        self.vvod_param_layout_grid.addWidget(self.dalnost_poleta_VTO_lineedit, 4, 1, 1, 1)
        self.kolvo_zelei_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.kolvo_zelei_label.setObjectName("kolvo_zelei_label")
        self.vvod_param_layout_grid.addWidget(self.kolvo_zelei_label, 0, 0, 1, 1)
        self.dalnost_poleta_VTO_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.dalnost_poleta_VTO_label.setObjectName("dalnost_poleta_VTO_label")
        self.vvod_param_layout_grid.addWidget(self.dalnost_poleta_VTO_label, 4, 0, 1, 1)
        self.SKO_VTO_linedit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.SKO_VTO_linedit.setAlignment(QtCore.Qt.AlignCenter)
        self.SKO_VTO_linedit.setObjectName("SKO_VTO_linedit")
        self.vvod_param_layout_grid.addWidget(self.SKO_VTO_linedit, 5, 1, 1, 1)
        self.vivod_avg_percent_damage_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.vivod_avg_percent_damage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vivod_avg_percent_damage_label.setObjectName("vivod_avg_percent_damage_label")
        self.vvod_param_layout_grid.addWidget(self.vivod_avg_percent_damage_label, 6, 1, 1, 1)
        self.auto_gen_kolvo_VTO_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_kolvo_VTO_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_kolvo_VTO_button.setObjectName("auto_gen_kolvo_VTO_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_kolvo_VTO_button, 1, 2, 1, 1)
        self.auto_gen_kolvo_ispitaniy_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_kolvo_ispitaniy_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_kolvo_ispitaniy_button.setObjectName("auto_gen_kolvo_ispitaniy_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_kolvo_ispitaniy_button, 2, 2, 1, 1)
        self.vivod_veroyat_porazh_vseh_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.vivod_veroyat_porazh_vseh_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vivod_veroyat_porazh_vseh_label.setObjectName("vivod_veroyat_porazh_vseh_label")
        self.vvod_param_layout_grid.addWidget(self.vivod_veroyat_porazh_vseh_label, 7, 1, 1, 1)
        self.auto_gen_kolvo_zelei_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_kolvo_zelei_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_kolvo_zelei_button.setObjectName("auto_gen_kolvo_zelei_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_kolvo_zelei_button, 0, 2, 1, 1)
        self.auto_gen_dalnost_poleta_VTO_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_dalnost_poleta_VTO_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_dalnost_poleta_VTO_button.setObjectName("auto_gen_dalnost_poleta_VTO_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_dalnost_poleta_VTO_button, 4, 2, 1, 1)
        self.auto_gen_radius_porazh_VTO_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_radius_porazh_VTO_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_radius_porazh_VTO_button.setObjectName("auto_gen_radius_porazh_VTO_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_radius_porazh_VTO_button, 3, 2, 1, 1)
        self.auto_gen_SKO_VTO_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_SKO_VTO_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_SKO_VTO_button.setObjectName("auto_gen_SKO_VTO_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_SKO_VTO_button, 5, 2, 1, 1)
        self.auto_gen_all_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.auto_gen_all_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.auto_gen_all_button.setObjectName("auto_gen_all_button")
        self.vvod_param_layout_grid.addWidget(self.auto_gen_all_button, 6, 2, 1, 1)
        self.monte_karlo_draw_graph_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.monte_karlo_draw_graph_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.monte_karlo_draw_graph_button.setObjectName("monte_karlo_draw_graph_button")
        self.vvod_param_layout_grid.addWidget(self.monte_karlo_draw_graph_button, 7, 2, 1, 1)
        self.monte_karlo_layout_vertical.addLayout(self.vvod_param_layout_grid)
        self.monte_karlo_graph = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.monte_karlo_graph.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.monte_karlo_graph.setObjectName("monte_karlo_graph")
        self.monte_karlo_layout_vertical.addWidget(self.monte_karlo_graph)
        self.monte_karlo_view_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.monte_karlo_view_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.monte_karlo_view_button.setObjectName("monte_karlo_view_button")
        self.monte_karlo_layout_vertical.addWidget(self.monte_karlo_view_button)
        self.main_layout_horizontal.addLayout(self.monte_karlo_layout_vertical)
        Deikstra_Monte_Karlo_Task_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Deikstra_Monte_Karlo_Task_Window)
        self.statusbar.setObjectName("statusbar")
        Deikstra_Monte_Karlo_Task_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Deikstra_Monte_Karlo_Task_Window)
        QtCore.QMetaObject.connectSlotsByName(Deikstra_Monte_Karlo_Task_Window)

    def retranslateUi(self, Deikstra_Monte_Karlo_Task_Window):
        _translate = QtCore.QCoreApplication.translate
        Deikstra_Monte_Karlo_Task_Window.setWindowTitle(_translate("Deikstra_Monte_Karlo_Task_Window", "Deikstra_Monte_Karlo_Task"))
        self.kolvo_vershin_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Вершин в графе"))
        self.start_point_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Начальная точка"))
        self.deikstra_draw_graph_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Построить граф"))
        self.end_point_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Конечная точка"))
        self.autogeneration_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.find_optimum_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Найти оптимальный маршрут"))
        self.vvod_matrix_textedit.setHtml(_translate("Deikstra_Monte_Karlo_Task_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ввод весов матрицы для ориентированного графа построчно через пробел<br />Пример матрицы рамерностью 5 на 5:<br />0 2 3 4 5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3 0 4 3 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 2 0 3 4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4 3 2 0 1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5 4 3 2 0</p></body></html>"))
        self.deikstra_view_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Посмотреть алгоритм Дейкстры"))
        self.radius_porazh_VTO_lineedit.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0"))
        self.avg_percent_damage_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Средний процент повреждений:"))
        self.kolvo_zelei_lineedit.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0"))
        self.kolvo_VTO_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Количество ВТО:"))
        self.SKO_VTO_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "СКО ВТО:"))
        self.kolvo_ispitaniy_lineedit.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0"))
        self.kolvo_ispitaniy_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Количество испытаний:"))
        self.radius_porazh_VTO_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Радиус поражения ВТО:"))
        self.veroyat_porazh_vseh_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Вероятность поражения всей инфраструктуры:"))
        self.kolvo_VTO_lineedit.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0"))
        self.dalnost_poleta_VTO_lineedit.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0"))
        self.kolvo_zelei_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Количество целей:"))
        self.dalnost_poleta_VTO_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Дальность полета ВТО:"))
        self.SKO_VTO_linedit.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0"))
        self.vivod_avg_percent_damage_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0.0"))
        self.auto_gen_kolvo_VTO_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.auto_gen_kolvo_ispitaniy_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.vivod_veroyat_porazh_vseh_label.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "0.0"))
        self.auto_gen_kolvo_zelei_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.auto_gen_dalnost_poleta_VTO_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.auto_gen_radius_porazh_VTO_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.auto_gen_SKO_VTO_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация"))
        self.auto_gen_all_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Автогенерация всех значений"))
        self.monte_karlo_draw_graph_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Построить график"))
        self.monte_karlo_view_button.setText(_translate("Deikstra_Monte_Karlo_Task_Window", "Посмотреть метод Монте-Карло"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Deikstra_Monte_Karlo_Task_Window = QtWidgets.QMainWindow()
    ui = Ui_Deikstra_Monte_Karlo_Task_Window()
    ui.setupUi(Deikstra_Monte_Karlo_Task_Window)
    Deikstra_Monte_Karlo_Task_Window.show()
    sys.exit(app.exec_())
